using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.Transformations;

/// <summary>
/// Collection of transformation command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all transformation commands in the domain.
/// </summary>
[TypeCollection(typeof(ITransformationsCommand), typeof(ITransformationsCommand), typeof(TransformationsCommands))]
public abstract partial class TransformationsCommands : TypeCollectionBase<ITransformationsCommand>
{
}