using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.EndPoints;

/// <summary>
/// Collection of endpoint types for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(EndpointTypeBase),typeof(IEndpointType),typeof(EndpointTypes))]
public partial class EndpointTypes : TypeCollectionBase<EndpointTypeBase, IEndpointType>
{
}