using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.EndPoints;

/// <summary>
/// Collection of endpoint types for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection("FractalDataWorks.Web.Http.Abstractions.EndPoints.EndpointTypeBase", "EndpointTypes")]
public partial class EndpointTypes
{
}