using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Authentication.Abstractions;

namespace FractalDataWorks.Services.Authentication;

/// <summary>
/// Collection of authentication service types for OAuth, Entra, JWT, etc.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication service implementations.
/// </summary>
[TypeCollection(typeof(AuthenticationTypeBase<,,>), typeof(IAuthenticationType), typeof(AuthenticationServiceTypes))]
public abstract partial class AuthenticationServiceTypes : TypeCollectionBase<AuthenticationTypeBase<IAuthenticationService, IAuthenticationConfiguration, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>>, IAuthenticationType>
{
}