using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Authentication.Abstractions;

namespace FractalDataWorks.Services.Authentication;

/// <summary>
/// Collection of authentication command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication commands in the domain.
/// </summary>
[TypeCollection(typeof(IAuthenticationCommand), typeof(IAuthenticationCommand), typeof(AuthenticationCommands))]
public abstract partial class AuthenticationCommands : TypeCollectionBase<IAuthenticationCommand>
{
}