using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.DataGateway.Abstractions;

namespace FractalDataWorks.Services.DataGateway;

/// <summary>
/// Collection of data gateway service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(DataGatewayTypeBase<,,>), typeof(IDataGatewayServiceType), typeof(DataGatewayTypes))]
public partial class DataGatewayTypes : ServiceTypeCollectionBase<DataGatewayTypeBase<IDataService, IDataGatewaysConfiguration, IServiceFactory<IDataService, IDataGatewaysConfiguration>>, IDataGatewayServiceType, IDataService, IDataGatewaysConfiguration, IServiceFactory<IDataService, IDataGatewaysConfiguration>>
{
}