using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.DataGateway.Abstractions;
using FractalDataWorks.Services.Abstractions;

namespace FractalDataWorks.Services.DataGateway;

/// <summary>
/// Collection of data gateway service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(DataGatewayTypeBase<,,>), typeof(IDataGatewayServiceType), typeof(DataGatewayTypes))]
public partial class DataGatewayTypes : ServiceTypeCollectionBase<DataGatewayTypeBase<IGenericService, IDataGatewaysConfiguration, IServiceFactory<IGenericService, IDataGatewaysConfiguration>>, IDataGatewayServiceType, IGenericService, IDataGatewaysConfiguration, IServiceFactory<IGenericService, IDataGatewaysConfiguration>>
{
}