using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.DataContainers.Abstractions;

/// <summary>
/// Collection of data container types for dataset operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(DataContainerType), typeof(DataContainerType), typeof(DataContainerTypes))]
public partial class DataContainerTypes
{
}