using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.Authentication.Abstractions.Methods;

/// <summary>
/// Collection of authentication protocol types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication protocols in the domain.
/// </summary>
[TypeCollection(typeof(AuthenticationProtocolBase), typeof(IAuthenticationProtocol), typeof(AuthenticationProtocols))]
public abstract partial class AuthenticationProtocols : TypeCollectionBase<AuthenticationProtocolBase, IAuthenticationProtocol>
{
}
