using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.Authentication.Abstractions.Security;

/// <summary>
/// Collection of token types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all token types in the domain.
/// </summary>
[TypeCollection(typeof(TokenTypeBase), typeof(ITokenType), typeof(TokenTypes))]
public abstract partial class TokenTypes : TypeCollectionBase<TokenTypeBase, ITokenType>
{
}
