using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.Policies;

/// <summary>
/// Collection of rate limit policies for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection("FractalDataWorks.Web.Http.Abstractions.Policies.RateLimitPolicyBase", "RateLimitPolicies")]
public partial class RateLimitPolicies
{
}