using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Configuration.Abstractions;

/// <summary>
/// Collection of configuration change types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(ConfigurationChangeTypeBase), typeof(IConfigurationChangeType), typeof(ConfigurationChangeTypes))]
public static partial class ConfigurationChangeTypes
{
}