using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.Authentication.Abstractions.Methods;

/// <summary>
/// Collection of authentication method enhanced enums.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication methods in the domain.
/// </summary>
[TypeCollection(typeof(AuthenticationMethodBase), typeof(IAuthenticationMethod), typeof(AuthenticationMethods))]
public abstract partial class AuthenticationMethods : TypeCollectionBase<AuthenticationMethodBase, IAuthenticationMethod>
{
}