using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Execution.Abstractions;

namespace FractalDataWorks.Services.Execution;

/// <summary>
/// Collection of execution command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all execution commands in the domain.
/// </summary>
[TypeCollection(typeof(IExecutionCommand), typeof(IExecutionCommand), typeof(ExecutionCommands))]
public partial abstract class ExecutionCommands : TypeCollectionBase<IExecutionCommand>
{
}