using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Data.Abstractions;

namespace FractalDataWorks.Services.Data;

/// <summary>
/// Collection of data command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all data commands in the domain.
/// </summary>
[TypeCollection(typeof(IDataCommand), typeof(IDataCommand), typeof(DataCommands))]
public partial abstract class DataCommands : TypeCollectionBase<IDataCommand>
{
}