using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.Data.Abstractions;

namespace FractalDataWorks.Services.Data;

/// <summary>
/// Collection of data service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(DataTypeBase<,,>), typeof(IDataType), typeof(DataServiceTypes))]
public partial class DataServiceTypes : ServiceTypeCollectionBase<DataTypeBase<IDataService, IDataConfiguration, IDataServiceFactory<IDataService, IDataConfiguration>>, IDataType, IDataService, IDataConfiguration, IDataServiceFactory<IDataService, IDataConfiguration>>
{
}