using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.DataContainers.Abstractions;

namespace FractalDataWorks.DataContainers;

/// <summary>
/// Collection of data container types for dataset operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(DataContainerType), typeof(DataContainerType), typeof(DataContainerTypes))]
public partial abstract class DataContainerTypes : TypeCollectionBase<DataContainerType, IDataContainerType>
{
}