using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.Policies;

/// <summary>
/// Collection of rate limit policies for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(RateLimitPolicyBase), typeof(IRateLimitPolicy), typeof(RateLimitPolicies))]
public partial class RateLimitPolicies : TypeCollectionBase<RateLimitPolicyBase, IRateLimitPolicy>
{
}