using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.DataStores.Abstractions;
using FractalDataWorks.Configuration.Abstractions;
using FractalDataWorks.Services;

namespace FractalDataWorks.DataStores;

/// <summary>
/// Collection of data store service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(DataStoreTypeBase<,,>), typeof(IDataStoreType), typeof(DataStoreTypes))]
public partial class DataStoreTypes : ServiceTypeCollectionBase<DataStoreTypeBase<IDataStore, IFdwConfiguration, IServiceFactory<IDataStore, IFdwConfiguration>>, IDataStoreType, IDataStore, IFdwConfiguration, IServiceFactory<IDataStore, IFdwConfiguration>>
{
}

