using FractalDataWorks.ServiceTypes.Attributes;

namespace FractalDataWorks.Services.Scheduling.Abstractions;

/// <summary>
/// Collection of scheduler service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection("FractalDataWorks.Services.Scheduling.Abstractions.SchedulerTypeBase", "SchedulerTypes")]
public partial class SchedulerTypes
{
}