using FractalDataWorks.Abstractions;
using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.Abstractions;

namespace FractalDataWorks.Services.Scheduling.Abstractions;

/// <summary>
/// Collection of scheduler service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(SchedulerTypeBase<,,>), typeof(ISchedulerType), typeof(SchedulerTypes))]
public partial class SchedulerTypes : ServiceTypeCollectionBase<SchedulerTypeBase<IGenericSchedulingService, IServiceFactory<IGenericSchedulingService, ISchedulingConfiguration>, ISchedulingConfiguration>, ISchedulerType, IGenericSchedulingService, ISchedulingConfiguration, IServiceFactory<IGenericSchedulingService, ISchedulingConfiguration>>
{
}