using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.Authentication.Abstractions;
using FractalDataWorks.Services.Authentication.Abstractions.Security;

namespace FractalDataWorks.Services.Authentication;

/// <summary>
/// Collection of authentication service types for OAuth, Entra, JWT, etc.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all authentication service implementations.
/// </summary>
[ServiceTypeCollection(typeof(AuthenticationTypeBase<,,>), typeof(IAuthenticationType<,,>), typeof(AuthenticationServiceTypes))]
public partial class AuthenticationServiceTypes : ServiceTypeCollectionBase<AuthenticationTypeBase<IAuthenticationService, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>, IAuthenticationConfiguration>, IAuthenticationType<IAuthenticationService, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>, IAuthenticationConfiguration>, IAuthenticationService, IAuthenticationConfiguration, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>>
{
}