using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services;
using FractalDataWorks.Services.Abstractions;
using FractalDataWorks.Services.Transformations.Abstractions;

namespace FractalDataWorks.Services.Transformations;

/// <summary>
/// Collection of transformation service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(TransformationTypeBase<,,>), typeof(ITransformationType<,,>), typeof(TransformationTypes))]
public partial class TransformationTypes : ServiceTypeCollectionBase<TransformationTypeBase<ITransformationProvider, IServiceFactory<ITransformationProvider, ITransformationsConfiguration>, ITransformationsConfiguration>, ITransformationType<ITransformationProvider, IServiceFactory<ITransformationProvider, ITransformationsConfiguration>, ITransformationsConfiguration>, ITransformationProvider, ITransformationsConfiguration, IServiceFactory<ITransformationProvider, ITransformationsConfiguration>>
{
}