using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Abstractions;

namespace FractalDataWorks.Services.DataGateway;

/// <summary>
/// Collection of data gateway command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all data gateway commands in the domain.
/// </summary>
[TypeCollection(typeof(IDataCommand), typeof(IDataCommand), typeof(DataGatewayCommands))]
public abstract partial class DataGatewayCommands : TypeCollectionBase<IDataCommand>
{
}