using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.SecretManagers;

/// <summary>
/// Collection of secret manager command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all secret manager commands in the domain.
/// </summary>
[TypeCollection(typeof(ISecretManagerCommand), typeof(ISecretManagerCommand), typeof(SecretManagerCommands))]
public abstract partial class SecretManagerCommands : TypeCollectionBase<ISecretManagerCommand>
{
}