using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.Security;

/// <summary>
/// Collection of security methods for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(SecurityMethodBase), typeof(SecurityMethodBase),typeof(SecurityMethods))]
public partial class SecurityMethods : TypeCollectionBase<SecurityMethodBase, ISecurityMethod>
{
}