using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Web.Http.Abstractions.Security;

/// <summary>
/// Collection of security methods for HTTP operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection("FractalDataWorks.Web.Http.Abstractions.Security.SecurityMethodBase", "SecurityMethods")]
public partial class SecurityMethods
{
}