using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.SecretManagers.Abstractions;

namespace FractalDataWorks.Services.SecretManagers;

/// <summary>
/// Collection of secret management service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(SecretManagerTypeBase<,,>), typeof(ISecretManagerServiceType), typeof(SecretManagementTypes))]
public abstract partial class SecretManagementTypes : ServiceTypeCollectionBase<SecretManagerTypeBase<ISecretManagerService, ISecretManagerConfiguration, ISecretManagerServiceFactory<ISecretManagerService, ISecretManagerConfiguration>>, ISecretManagerServiceType, ISecretManagerService, ISecretManagerConfiguration, ISecretManagerServiceFactory<ISecretManagerService, ISecretManagerConfiguration>>
{
}