using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.SecretManagement.Abstractions;

namespace FractalDataWorks.Services.SecretManagement;

/// <summary>
/// Collection of secret management service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(SecretManagementTypeBase<,,>), typeof(ISecretManagementType), typeof(SecretManagementTypes))]
public partial class SecretManagementTypes : ServiceTypeCollectionBase<SecretManagementTypeBase<ISecretManagementService, ISecretManagementConfiguration, ISecretManagementFactory<ISecretManagementService, ISecretManagementConfiguration>>, ISecretManagementType, ISecretManagementService, ISecretManagementConfiguration, ISecretManagementFactory<ISecretManagementService, ISecretManagementConfiguration>>
{
}