using FractalDataWorks.ServiceTypes.Attributes;

namespace FractalDataWorks.Services.SecretManagement.Abstractions;

/// <summary>
/// Collection of secret management service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(SecretManagementTypeBase<,,>), typeof(ISecretManagementType), typeof(SecretManagementTypes))]
public partial class SecretManagementTypes
{
}