using FractalDataWorks.ServiceTypes.Attributes;

namespace FractalDataWorks.Services.Transformations.Abstractions;

/// <summary>
/// Collection of transformation service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection("FractalDataWorks.Services.Transformations.Abstractions.TransformationTypeBase", "TransformationTypes")]
public partial class TransformationTypes
{
}