using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.Services.Connections.Abstractions;

namespace FractalDataWorks.Services.Connections;

/// <summary>
/// Collection of connection command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all connection commands in the domain.
/// </summary>
[TypeCollection(typeof(IConnectionCommand), typeof(IConnectionCommand), typeof(ConnectionCommands))]
public abstract partial class ConnectionCommands : TypeCollectionBase<IConnectionCommand>
{
}