using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.MCP.Abstractions;

/// <summary>
/// Collection of all MCP tool types available in the framework.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(McpToolType), typeof(McpToolType), typeof(McpToolTypes))]
public partial class McpToolTypes
{
}