using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.DataStores.Abstractions;

/// <summary>
/// Collection of data store type metadata.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// DataStoreTypes provides access to metadata about storage backends (SQL Server, PostgreSQL, S3, FileSystem, etc.)
/// This is NOT a service collection - use TypeCollection pattern for type discovery.
/// </remarks>
[TypeCollection(typeof(DataStoreTypeBase), typeof(IDataStoreType), typeof(DataStoreTypes))]
public abstract partial class DataStoreTypes : TypeCollectionBase<DataStoreTypeBase, IDataStoreType>
{
}

