using FractalDataWorks.ServiceTypes;
using FractalDataWorks.ServiceTypes.Attributes;
using FractalDataWorks.Services.Authentication.Abstractions;

namespace FractalDataWorks.Services.Authentication;

/// <summary>
/// Collection of authentication service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection(typeof(AuthenticationTypeBase<,,>), typeof(IAuthenticationType), typeof(AuthenticationTypes))]
public partial class AuthenticationTypes : ServiceTypeCollectionBase<AuthenticationTypeBase<IAuthenticationService, IAuthenticationConfiguration, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>>, IAuthenticationType, IAuthenticationService, IAuthenticationConfiguration, IAuthenticationServiceFactory<IAuthenticationService, IAuthenticationConfiguration>>
{
}