using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;
using FractalDataWorks.MCP.Abstractions;

namespace FractalDataWorks.Services.MCP;

/// <summary>
/// Collection of all MCP tool types available in the framework.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(McpToolType), typeof(McpToolType), typeof(McpToolTypes))]
public abstract partial class McpToolTypes : TypeCollectionBase<McpToolType>
{
}