using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Configuration.Abstractions;

/// <summary>
/// Collection of configuration source types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
[TypeCollection(typeof(ConfigurationSourceTypeBase), typeof(IConfigurationSourceType), typeof(ConfigurationSourceTypes))]
public static partial class ConfigurationSourceTypes
{
}