using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Services.Scheduling;

/// <summary>
/// Collection of scheduling command types.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// Provides unified access to all scheduling commands in the domain.
/// </summary>
[TypeCollection(typeof(ISchedulingCommand), typeof(ISchedulingCommand), typeof(SchedulingCommands))]
public abstract partial class SchedulingCommands : TypeCollectionBase<ISchedulingCommand>
{
}