using FractalDataWorks.Collections;
using FractalDataWorks.Collections.Attributes;

namespace FractalDataWorks.Data.DataContainers.Abstractions;

/// <summary>
/// Collection of data container types for dataset operations.
/// Generated by TypeCollectionGenerator with high-performance lookups.
/// </summary>
/// <remarks>
/// DataContainerTypes provides access to metadata about data format types (CSV, JSON, Parquet, SqlTable, etc.)
/// This is NOT a service collection - use TypeCollection pattern for type discovery.
/// </remarks>
[TypeCollection(typeof(DataContainerTypeBase), typeof(IDataContainerType), typeof(DataContainerTypes))]
public abstract partial class DataContainerTypes : TypeCollectionBase<DataContainerTypeBase, IDataContainerType>
{
}