using FractalDataWorks.ServiceTypes.Attributes;

namespace FractalDataWorks.Services.Authentication.Abstractions;

/// <summary>
/// Collection of authentication service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection("FractalDataWorks.Services.Authentication.Abstractions.AuthenticationTypeBase", "AuthenticationTypes")]
public partial class AuthenticationTypes
{
}