name: Publish to GitHub Packages

on:
  push:
    branches:
      - master   # Publish stable releases (0.1.0)
      - develop  # Publish pre-release packages (0.1.0-alpha.123)
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish to GitHub Packages
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for GitVersioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Install Nerdbank.GitVersioning
        run: dotnet tool install -g nbgv

      - name: Get version from Nerdbank.GitVersioning
        id: nbgv
        run: |
          $version = nbgv get-version -f json | ConvertFrom-Json
          Write-Host "Version: $($version.NuGetPackageVersion)"
          Write-Host "AssemblyVersion: $($version.AssemblyVersion)"
          Write-Host "SimpleVersion: $($version.SimpleVersion)"
          Write-Output "nuget_version=$($version.NuGetPackageVersion)" >> $env:GITHUB_OUTPUT
          Write-Output "assembly_version=$($version.AssemblyVersion)" >> $env:GITHUB_OUTPUT
          Write-Output "simple_version=$($version.SimpleVersion)" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore

      - name: Discover all projects
        id: discover
        shell: pwsh
        run: |
          $allProjects = Get-ChildItem -Path src -Filter "*.csproj" -Recurse -File |
            Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" }

          Write-Host "All projects to package:"
          $allProjects | ForEach-Object { Write-Host "  - $($_.BaseName)" }

          # Count projects
          Write-Output "project_count=$($allProjects.Count)" >> $env:GITHUB_OUTPUT

      - name: Build all projects
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        continue-on-error: true

      - name: Pack NuGet packages
        shell: pwsh
        run: |
          $allProjects = Get-ChildItem -Path src -Filter "*.csproj" -Recurse -File |
            Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" }

          $packaged = 0

          # Create artifacts directory
          New-Item -ItemType Directory -Path "artifacts" -Force | Out-Null

          foreach ($csprojFile in $allProjects) {
            Write-Host "Packing: $($csprojFile.BaseName)" -ForegroundColor Cyan

            dotnet pack $csprojFile.FullName `
              --configuration Release `
              --no-build `
              --output artifacts `
              /p:IncludeSymbols=true `
              /p:SymbolPackageFormat=snupkg

            if ($LASTEXITCODE -eq 0) {
              Write-Host "  ✓ Packed: $($csprojFile.BaseName)" -ForegroundColor Green
              $packaged++
            } else {
              Write-Host "  ✗ Failed: $($csprojFile.BaseName)" -ForegroundColor Red
            }
          }

          Write-Host ""
          Write-Host "Packaged $packaged projects" -ForegroundColor Green

      - name: List packages
        shell: pwsh
        run: |
          Write-Host "NuGet packages created:" -ForegroundColor Cyan
          Get-ChildItem -Path artifacts -Filter "*.nupkg" | ForEach-Object {
            Write-Host "  - $($_.Name)" -ForegroundColor Green
          }

          Write-Host ""
          Write-Host "Symbol packages created:" -ForegroundColor Cyan
          Get-ChildItem -Path artifacts -Filter "*.snupkg" | ForEach-Object {
            Write-Host "  - $($_.Name)" -ForegroundColor Green
          }

      - name: Publish to GitHub Packages
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $packages = Get-ChildItem -Path artifacts -Filter "*.nupkg" | Where-Object { $_.Name -notlike "*.symbols.nupkg" }

          foreach ($package in $packages) {
            Write-Host "Publishing: $($package.Name)" -ForegroundColor Cyan

            dotnet nuget push $package.FullName `
              --source https://nuget.pkg.github.com/CyberdineDevelopment/index.json `
              --api-key $env:GITHUB_TOKEN `
              --skip-duplicate

            if ($LASTEXITCODE -eq 0) {
              Write-Host "  ✓ Published: $($package.Name)" -ForegroundColor Green
            } else {
              Write-Host "  ✗ Failed: $($package.Name)" -ForegroundColor Red
            }
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg
          retention-days: 90

      - name: Summary
        shell: pwsh
        run: |
          $summary = @"
          ### GitHub Packages Publishing Complete ✓

          **Version:** ${{ steps.nbgv.outputs.nuget_version }}
          **Published:** ${{ steps.discover.outputs.project_count }} packages
          **Target:** GitHub Packages (Private - organization members only)
          **Branch:** ${{ github.ref_name }}

          All packages (public and private) are now available on GitHub Packages for internal use.

          ## Using these packages

          Add the GitHub Packages source:
          \`\`\`bash
          dotnet nuget add source https://nuget.pkg.github.com/CyberdineDevelopment/index.json \
            --name github \
            --username YOUR_GITHUB_USERNAME \
            --password YOUR_GITHUB_PAT
          \`\`\`

          Install any package:
          \`\`\`bash
          dotnet add package FractalDataWorks.Results --version ${{ steps.nbgv.outputs.nuget_version }}
          dotnet add package FractalDataWorks.Services.Authentication --version ${{ steps.nbgv.outputs.nuget_version }}
          dotnet add package FractalDataWorks.Services.SecretManagers.AzureKeyVault --version ${{ steps.nbgv.outputs.nuget_version }}
          \`\`\`

          **Note:** Public packages are also published to NuGet.org from the public repository mirror.
          "@

          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding UTF8
