using FractalDataWorks.ServiceTypes.Attributes;

namespace FractalDataWorks.Services.DataGateway.Abstractions;

/// <summary>
/// Collection of data gateway service types.
/// Generated by ServiceTypeCollectionGenerator with high-performance lookups.
/// </summary>
[ServiceTypeCollection("FractalDataWorks.Services.DataGateway.Abstractions.DataGatewayTypeBase", "DataGatewayTypes")]
public partial class DataGatewayTypes
{
}